### ISSUE TITLE
Change aspect ratio

### ISSUE THREAD

**Issue by pantumaca** [farmerbb/SecondScreen#66]
Hi there.

Is it possible to add an option to change the aspect ratio from the phone's default to 16:9? It would be something similar as Samsung's Smart View app does when you mirror the screen.

This could be useful when you only want to mirror the screen for watching a movie or serie (from Netflix, Amazon Prime video or weather app used) and avoid black bars at the top and bottom of the TV due to different aspect ratio between phone and TV 

I think this option is less intrusive than changing resolution.

 
Thanks.

**Comment by jise** [comment]
When you read what this application does or does not do, then you realize that your request is actually completely pointless.

> This app does not provide screen mirroring capabilities on its own. Screen mirroring may require either an MHL/SlimPort adapter or a wireless solution such as Miracast or Chromecast.

In other words, you can't do this other than change the current resolution of your phone to get a 16: 9 aspect ratio for projection on TV. And this is exactly what this application allows perfectly. Is it clear to you?

**Comment by pantumaca** [comment]
Do you have any problem with me? Keep calm...

I am not asking for any screen mirroring capability. The phones with HDMI out function get the signal at 1080p but with an aspect ratio corresponding to the phone.

My question was if it is possible to just change the aspect ratio with a new option (and like example I talked about Samsung's app "Smart View" to be more clear what I am talking about). That is all.

But hey, I hope your Excellence could forgive me for making a question

**Comment by jise** [comment]
It's not about you at all, don't take it personally. I'm absolutely calm. On your question I came by accident when I looked at this site what are the current issues. By the way, asking here is absolutely fine of course. I just dared to point out that your question really doesn't make sense.

1. I'm an ordinary user just like you, I'm not the author of this great app.
2. Explain to me how you would like to change the aspect ratio without changing the resolution. After all, the aspect ratio is defined by resolution (the ratio of the width to the height of an image or screen).
3. What exactly do you mind about changing the resolution? After all, you only do it for a while, when you project it on TV and on the TV screen you will see exactly what your mobile will display when you change the resolution. You will end the screening, return to your native resolution.

I myself programmed a two-state widget in Tasker using SecondScreen as plugin that changes the screen resolution and density. One click on my dynamic widget to switch to native phone resolution and my preferred density (if %DR_STATE=1), second click on widget to switch to 16:9 TV resolution (if %DR_STATE=0) and so on.
I use it very often and I am very satisfied with it.

https://zentalk.asus.com/en/discussion/14283/mirror-movie-4-3-aspects-ratio

**Comment by farmerbb** [comment]
Let's please keep this discussion civil. That having been said, @jise is correct here in that you can't change the aspect ratio of the display without inherently changing the resolution.

I should clarify that SecondScreen does not actually change the output of the physical connection between your phone and the secondary display - if it outputs at 1080p, then it'll continue outputting at 1080p when using SecondScreen.  The app's primary function is to change the resolution of your phone's display so that it can better match your secondary display, _especially_ when the aspect ratio differs between the two.

@pantumaca if you haven't yet tried SecondScreen for yourself, I encourage you to do so as you'll find that the app already does exactly what you're wanting it to do.
